### ISSUE TITLE
[Feature Request] More custom themes.

### ISSUE THREAD

**Issue by SainoNamkho** [bggRGjQaUbCoE/c001apk-compose#14]
#1 之后加入了custom主题，希望可以进一步自定义各个元素的颜色，而不只是 `seedColor`.

个人需要的配色是白底黑字、强调色只影响控件和标题（其实酷安绿挺好的）。

原因如下：
默认的 dynamic scheme 调色板总是会影响背景颜色，好处是看着 Material Design 味更浓了，坏处是阅读起来很累。

这个配色机制适合 UI 元素（和标题标签字体）的展示，对于大段小字体文本阅读，带颜色的纯色背景都不如黑白灰清晰。

![IMG_20240914_060002](https://github.com/user-attachments/assets/9e262207-5234-4cc3-af9a-fca95f04a918)

虽然背景很接近 `#ffffff` 但差这一点点就是不能设成纯白，色调还是很明显，而且直接承载文字的卡片比后面的背景颜色更重。带来的结果是
- 对比度低，字多了读着就类
- 暖色背景看着容易犯困（如果同时开着护眼模式就更困了）、冷色背景看久了眼睛比较疲劳，如果是绿色调观感上还会显得屏幕素质不高。

以上都是个人审美，最下层背景带颜色问题不大，但确实需要一个纯白/灰色的卡片背景色选项，最终还是请您酌定（如果敲定了设计我来 pr 也可以），感谢！

**Comment by SainoNamkho** [comment]
![IMG_20240914_060114](https://github.com/user-attachments/assets/2d468b3a-5a93-44d9-8b7c-2929243cddef)

**Comment by bggRGjQaUbCoE** [comment]
感谢反馈
纯白跟MD3不搭
卡片背景会选较浅的颜色
后续提供PaletteStyle选项，想要黑白灰可以选择`Monochrome`或者`Neutral`

**Comment by SainoNamkho** [comment]
> 感谢反馈 纯白跟MD3不搭 卡片背景会选较浅的颜色 后续提供PaletteStyle选项，想要黑白灰可以选择`Monochrome`或者`Neutral`

感谢！
