### ISSUE TITLE
一个ui问题

### ISSUE THREAD

**Issue by zero24345** [bggRGjQaUbCoE/c001apk-compose#3]
系统版本为hp1.0.24.4.8dev
机型为 redmi 12t
应用版本为b4fb380(40)
 
点击图片后，查看原图位于屏幕打孔处无法点击![Screenshot_20240629-104949.png](https://github.com/bggRGjQaUbCoE/c001apk-compose/assets/114745061/6ebc8c51-e659-4a30-87e2-03f7b6f47b1a)

**Comment by bggRGjQaUbCoE** [comment]
OK
