### ISSUE TITLE
点击话题报错

### ISSUE THREAD

**Issue by WoAiNianChu** [bggRGjQaUbCoE/c001apk-compose#6]
随便点击一个话题就会报出
**java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 1591 path $.data.tag_pics** 错误
一加ace3 Android 14
![1000005864_小萌GIF_20240713_144409.gif](https://github.com/user-attachments/assets/3703c222-46c4-45ca-af3e-d6c666d561b5)

**Comment by bggRGjQaUbCoE** [comment]
没问题，自己检查api version
