### ISSUE TITLE
按键不适配

### ISSUE THREAD

**Issue by Afire-625** [bggRGjQaUbCoE/c001apk-compose#9]

**Comment by Afire-625** [comment]
![Screenshot_2024-07-21-18-30-40-520_com.example.c001apk.compose.jpg](https://github.com/user-attachments/assets/bd8d2d7b-6a85-4110-9839-7b765bca83b2)

**Comment by Afire-625** [comment]
![Screenshot_2024-07-21-18-30-40-520_com.example.c001apk.compose.jpg](https://github.com/user-attachments/assets/bd8d2d7b-6a85-4110-9839-7b765bca83b2)

无法点按《查看原图按钮》

**Comment by Afire-625** [comment]
![Screenshot_2024-07-21-18-30-40-520_com.example.c001apk.compose.jpg](https://github.com/user-attachments/assets/bd8d2d7b-6a85-4110-9839-7b765bca83b2)

无法点按《查看原图》按钮，顶到状态栏上边去了

**Comment by bggRGjQaUbCoE** [comment]
dup #3
